services:
  postgres:
    image: postgres:16
    container_name: myapp_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: application
    volumes:
      - ./volumes:/var/lib/postgresql/data
